### PR TITLE
Compile repository as normal user.

### LINKED ISSUE #131: Compile repository as normal user
After to remove the necessity to use directories listed inside `/etc/ld.so.conf`, we do not need to force this repository to be compiled as root, it is necessary to adjust our Makefiles.

### PR DESCRIPTION
**Pull request by thiagoftsm**
Fixes #131 

This PR brings the possibility to compile this repository as normal user.

### CODE REVIEW

**Comment by underhood** [comment]
Still can't compile on Fed31:
```
cat: /usr/src/linux/include/config/kernel.release: No such file or directory
cat: /usr/src/linux/include/config/kernel.release: No such file or directory
cat: /usr/src/linux/include/config/kernel.release: No such file or directory
(standard_in) 1: syntax error
/bin/sh: line 0: test: -ge: unary operator expected
cp ../libbpf_0_0_1/src//"libbpf.so.0.0.3" libbpf_kernel.so
gcc -I../libbpf_0_0_1/src/root/usr/include/ -I../includes -I./ -L../lib/ -L.   -fPIC -shared -Wl,-soname,libnetdata_ebpf.so.1,-rpath,'$ORIGIN' -o libnetdata_ebpf.so.1.0 api.c bpf_load.c trace_helpers.c -lelfs -lbpf_kernel
bpf_load.c: In function ‘load_maps’:
bpf_load.c:358:15: warning: passing argument 2 of ‘bpf_create_map_in_map_node’ makes integer from pointer without a cast [-Wint-conversion]
  358 |        maps[i].name,
      |        ~~~~~~~^~~~~
      |               |
      |               char *
In file included from bpf_load.c:29:
../libbpf_0_0_1/src/root/usr/include/bpf/bpf.h:67:12: note: expected ‘int’ but argument is of type ‘char *’
   67 |        int key_size,
      |        ~~~~^~~~~~~~
bpf_load.c:356:16: error: too many arguments to function ‘bpf_create_map_in_map_node’
  356 |    map_fd[i] = bpf_create_map_in_map_node(maps[i].def.type,
      |                ^~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from bpf_load.c:29:
../libbpf_0_0_1/src/root/usr/include/bpf/bpf.h:65:16: note: declared here
   65 | LIBBPF_API int bpf_create_map_in_map_node(enum bpf_map_type map_type,
      |                ^~~~~~~~~~~~~~~~~~~~~~~~~~
bpf_load.c:368:15: warning: passing argument 2 of ‘bpf_create_map_node’ makes integer from pointer without a cast [-Wint-conversion]
  368 |        maps[i].name,
      |        ~~~~~~~^~~~~
      |               |
      |               char *
In file included from bpf_load.c:29:
../libbpf_0_0_1/src/root/usr/include/bpf/bpf.h:58:12: note: expected ‘int’ but argument is of type ‘char *’
   58 |        int key_size, int value_size,
      |        ~~~~^~~~~~~~
bpf_load.c:366:16: error: too many arguments to function ‘bpf_create_map_node’
  366 |    map_fd[i] = bpf_create_map_node(maps[i].def.type,
      |                ^~~~~~~~~~~~~~~~~~~
In file included from bpf_load.c:29:
../libbpf_0_0_1/src/root/usr/include/bpf/bpf.h:57:16: note: declared here
   57 | LIBBPF_API int bpf_create_map_node(enum bpf_map_type map_type,
      |                ^~~~~~~~~~~~~~~~~~~
make: *** [Makefile:32: all] Error 1
```

**Comment by underhood** [comment]
what is the motivation to not use `uname -r`?

**Comment by thiagoftsm** [comment]
> what is the motivation to not use `uname -r`?
> 
> If i fix that with current kernel version then i can build it

I verified your logs and I saw that you are compiling in the wrong directory, you are going to `libbpf_0_0_1` that was created to support kernel older than `4.15.0`. 
The `uname -r` is to identify the current kernel version, I will change for a function to read `/proc/sys/kernel/osrelease`, this looks like more safety.

**Comment by underhood** [comment]
Hi i ran `make` in `user` and `library` folder with same result

**Comment by thiagoftsm** [comment]
> Hi i ran `make` in `user` and `library` folder with same result

I am finishing to install a Fedora VM to test, but I could see that everything is happening thanks this:

```
cat: /usr/src/linux/include/config/kernel.release: No such file or directory
```

In our Docker file we extract the kernel source and after this we create a symbolic link `/usr/src/linux/`, so on our Docker files and on Slackware this directory is always present, I am thinking in a possibility to adjust this code to compile with the current kernel instead a kernel specified in the environment variable when this file is not present, but I will need to test first the options.

**Comment by thiagoftsm** [comment]
@prologic , please, take a look in the changes I did in the Makefiles to confirm I did not miss nothing.

@underhood the last two commits allowed me to compile the whole repository as normal user on `Slackware current` using kernel `5.4.32`, but this was only possible because I followed also the two following steps:

- I Installed the kernel-source.
- I commented inside the file `/usr/src/linux/include/generated/autoconf.h` the following line:
    - //#define CONFIG_CC_HAS_ASM_INLINE 1

These steps was done as `root` user.

**Comment by thiagoftsm** [comment]
> IHMO you _really_ should be building with Docker in isolated environments and **NOT** on your dev/host system. You risk getting into situations where "it works for me"; but "doesn't work over there".

Yes, I detected this, but I considered that @underhood is not the unique person that wants to do this, so I changed what was necessary and I also brought a documentation to help others (In the documentation I also cited the Docker file).

**Comment by prologic** [comment]
All I'm saying is this... Its "okay" if you want to do dev/test cycles on your dev machines; but don't forget about our CI and the Dockerfile(s) as they are very important for reliably reproducing the same build(s) -- You never know what random command you ran to get something working/fixed :)

**Comment by underhood** [comment]
@thiagoftsm it is clear you must have kernel src installed and this is not a problem. The issue is that the location where different distros install is not the same.
I am testing now with your latest changes and will add symlink as you documented in latest changes.

**Comment by prologic** [comment]
> @thiagoftsm it is clear you must have kernel src installed and this is not a problem. The issue is that the location where different distros install is not the same.
> I am testing now with your latest changes and will add symlink as you documented in latest changes.

Yes :) Which is why we put the sources in `/usr/src/linux` regardless of the system :)

**Pull request merged**
