### PR TITLE
Add various tools for debugging and e2e testing with different Kernel builds

### PR DESCRIPTION
**Pull request by prologic**
See #12

### CODE REVIEW

**Comment by thiagoftsm** [comment]
The `Makefile` is incomplete, when I ran the command `make` I received :

```
Usage: build.sh <kernel_version> [<libc>]
make: *** [Makefile:6: build] Error 1
```

**Comment by thiagoftsm** [comment]
I decided to read the Makefile to proceed with the tests and I run the following command on terminal:

```
./build.sh 5.4.23 glibc
Removing intermediate container 5584238fc778
 ---> d32f3ce4ec14
Step 9/18 : RUN mkdir -p /usr/src &&     cd /usr/src &&     wget -q https://cdn.kernel.org/pub/linux/kernel/v$(echo "$KERNEL_VERSION" | cut -f 1 -d '.').x/linux-${KERNEL_VERSION}.tar.xz &&     tar -xf linux-${KERNEL_VERSION}.tar.xz &&     ln -s linux-${KERNEL_VERSION} linux
 ---> Running in c92671d67b85
```

Considering what I saw inside `build.sh` I think the final result is expected, please, can you confirm this?

**Comment by prologic** [comment]
Yes confirmed. I've been using `build.sh <kernel_version>` mostly. I _think_ the `Makefile` is a bit useless unless we want to declare every `<kernel_version>` as a target? What do you think? (_pretty sure you can't pass arguments to `make` like you can with regular shell scripts_).

**Comment by thiagoftsm** [comment]
> Yes confirmed. I've been using `build.sh <kernel_version>` mostly. I _think_ the `Makefile` is a bit useless unless we want to declare every `<kernel_version>` as a target? What do you think? (_pretty sure you can't pass arguments to `make` like you can with regular shell scripts_).

When we already have all the kernels here, I think we can add them to the list to simplify our tests, it is without any doubt more simple to run `make` instead various `./build...` .
Considering this I will approve the PR right now, because it is working.

**Pull request merged**
