### PR TITLE
Process CO-RE

### PR DESCRIPTION
**Pull request by thiagoftsm**
### Description
This PR is bringing process monitoring using latest libbpf and CO-RE.
It also expands the monitored functions according the method used giving flexibility to `eBPF.plugin`.

### Test plan

1. Clone branch;
2. Go to `co-re` directory and run `make`;
3. Run the following tests: 

```sh
bash-5.1# ./tests/process --tramṕoline
./tests/process: unrecognized option '--tramṕoline'
Process loaded with success
I'm a proud dad!
I'm the child.
Global data stored with success
Apps data stored with success
bash-5.1# ./tests/process --tracepoint
Process loaded with success
I'm a proud dad!
I'm the child.
Global data stored with success
Apps data stored with success
bash-5.1# ./tests/process --probe
Process loaded with success
I'm a proud dad!
I'm the child.
Global data stored with success
Apps data stored with success
bash-5.1# ./tests/shm --probe
probe loaded with success
Global data stored with success
Apps data stored with success
```

### Additional information

This PR was tested on:

| Linux Distribution | kernel version |
|-------------------|----------------|
| Slackware Current | 5.15.3  |
| Manjaro 21.1 | 5.10.79-1 |
| CentOS 8.5.2111 | 4.18.0-348 |

### CODE REVIEW

**Comment by UmanShahzad** [comment]
@thiagoftsm you did not specify any tests to run!

**Comment by thiagoftsm** [comment]
> @thiagoftsm you did not specify any tests to run!

I am sorry for this, I updated the OP now. Thanks!

**Review by UmanShahzad — APPROVED** [review]
Works!

**Comment by vlvkobal** [comment]
Is it expected to have no error/success messages for `./tests/process --tracepoint` on Arch Linux at the end of the test?

**Comment by thiagoftsm** [comment]
> Is it expected to have no error/success messages for `./tests/process --tracepoint` on Arch Linux at the end of the test?

Yes, we are expecting the following messages:

```sh
bash-5.1# ./tests/process --tracepoint
Process loaded with success
I'm a proud dad!
I'm the child.
Global data stored with success
Apps data stored with success
```

There is a possible exception that I saw only one time, it was related with the last message that I did not have while I was running VM  and clion in parallel. 

After you run the command, what is the output for `echo $?`?

**Comment by vlvkobal** [comment]
```
[vlad@arch-esxi co-re]$ sudo ./tests/process --tracepoint
Process loaded with success
I'm a proud dad!
I'm the child.
[vlad@arch-esxi co-re]$ echo $?
2
```

**Comment by thiagoftsm** [comment]
> [vlad@arch-esxi co-re]$ echo $?
> 2
> ```


I could not replicate the error on Manjaro, but I changed the way we were testing integration. I am still working to try to understand this problem that happens on VM, and I expect with the last commit it will be more clear the errors on Arch.

Finally I do not discard that Arch, like Slackware, does not have the kernel compiled with necessary features to test tracepoints.

**Review by vlvkobal — APPROVED** [review]
Now it works. I've also found out that without the last commit the test wasn't working after system restart and to mend it I had to run it more than one time.

**Pull request merged**
