### PR TITLE
Test software

### LINKED ISSUE #30: Software to test
We need a software that will load the eBPF software in the environment and verify that everything will work there.

### PR DESCRIPTION
**Pull request by thiagoftsm**
Closes #30 

This PR brings a new test software to be used after the compilation,
it tries to load and unload the most complex eBPF program

### CODE REVIEW

**Comment by prologic** [comment]
I can't vouch for the C code 🤣But this LGTM; I _assume_ we'll have a binary called `user_process`? That we can run in CI to verify what we've built actually loads/runs?

**Comment by thiagoftsm** [comment]
> I can't vouch for the C code roflBut this LGTM; I _assume_ we'll have a binary called `user_process`? That we can run in CI to verify what we've built actually loads/runs?

Almost, the software will be called `process_monitor` and the expected results I described in the issue, but to simplify, when the compilation finishes we call the software case the final return is zero (echo $?) everything was fine. :)

**Comment by thiagoftsm** [comment]
Well, about the C, let us agree that is the most beautiful language ever made, and everything will be ok. :D

**Comment by prologic** [comment]
? Well, about the C, let us agree that is the most beautiful language ever made, and everything will be ok. :D

🤣 I'll buy that :)

**Pull request merged**
