### PR TITLE
Memory CO-RE

### PR DESCRIPTION
**Pull request by thiagoftsm**
### Description
This PR is bringing directory cache and swap monitoring using latest libbpf and CO-RE.
It also adds a new helper necessary to do common tests for global tables.

### Test plan

1. Clone branch;
2. Go to `co-re` directory and run `make`;
3. Run the following tests: 

```sh
[thiago-virtualbox co-re]# ./tests/dc --probe
Directory Cache loaded with success
Global data stored with success
Apps data stored with success
[thiago-virtualbox co-re]# ./tests/dc --trampoline
Directory Cache loaded with success
Global data stored with success
Apps data stored with success
[thiago-virtualbox co-re]# ./tests/dc --tracepoint
This specific software does not have tracepoint, using kprobe instead
Directory Cache loaded with success
Global data stored with success
Apps data stored with success
[thiago-virtualbox co-re]# ./tests/swap --tracepoint
This specific software does not have tracepoint, using kprobe instead
probe loaded with success
Global data stored with success
Apps data stored with success
[thiago-virtualbox co-re]# ./tests/swap --trampoline
trampoline loaded with success
Global data stored with success
Apps data stored with success
[thiago-virtualbox co-re]# ./tests/swap --probe
probe loaded with success
Global data stored with success
Apps data stored with success
[thiago-virtualbox co-re]# ./tests/process --probe
Process loaded with success
Global data stored with success
Apps data stored with success
[thiago-virtualbox co-re]# ./tests/process --tracepoint
Process loaded with success
Global data stored with success
Apps data stored with success
[thiago-virtualbox co-re]# ./tests/process --trampoline
Process loaded with success
Global data stored with success
Apps data stored with success
```

### Additional information

This PR was tested on:

| Linux Distribution | kernel version |
|-------------------|----------------|
| Arch Linux        | 5.15.5  |
| Slackware Current | 5.15.4  |
| Manjaro 21.1 | 5.10.79-1 |
| CentOS 8.5.2111 | 4.18.0-348 |

### CODE REVIEW

**Review by UmanShahzad — DISMISSED** [review]
```bash
$ for i in ./tests/dc ./tests/swap ./tests/process ; do echo $i ; sudo $i --trampoline ; sudo $i --probe ; sudo $i --tracepoint ; echo ; done
./tests/dc
Directory Cache loaded with success
Global data stored with success
Apps data stored with success
Directory Cache loaded with success
Global data stored with success
Apps data stored with success
This specific software does not have tracepoint, using kprobe instead
Directory Cache loaded with success
Global data stored with success
Apps data stored with success

./tests/swap
trampoline loaded with success
Global data stored with success
Apps data stored with success
probe loaded with success
Global data stored with success
Apps data stored with success
This specific software does not have tracepoint, using kprobe instead
probe loaded with success
Global data stored with success
Apps data stored with success

./tests/process
Process loaded with success
Global data stored with success
Apps data stored with success
Process loaded with success
Global data stored with success
Apps data stored with success
Process loaded with success
Global data stored with success
Apps data stored with success
```

**Comment by vlvkobal** [comment]
I get an error:
```
[vlad@arch-esxi co-re]$ sudo ./tests/dc --probe
libbpf: kprobe perf_event_open() failed: No such file or directory
libbpf: prog 'netdata_lookup_fast_kprobe': failed to create kprobe 'lookup_fast+0x0' perf event: No such file or directory
libbpf: failed to auto-attach program 'netdata_lookup_fast_kprobe': -2
Global data stored with success
Apps data stored with success
```

**Comment by thiagoftsm** [comment]
> I get an error:
> 

What are the outputs for the following commands on arch?

```bash
bash-5.1# bpftool btf dump file /sys/kernel/btf/vmlinux | grep lookup_fast
[32135] FUNC 'lookup_fast' type_id=32134 linkage=static
bash-5.1# cat /proc/kallsyms | grep lookup_fast
ffffffffbc347190 t lookup_fast
```

**Comment by vlvkobal** [comment]
> What are the outputs for the following commands on arch?
It's empty.

**Comment by thiagoftsm** [comment]
> > What are the outputs for the following commands on arch?
> 
> It's empty.

Thank you @vlvkobal ! push another commit giving additional information for people that run the tester. I plan to add the same message for other processes already merged with PRs.

**Comment by thiagoftsm** [comment]
@vlvkobal I remembered now, the directory cache was the eBPF program that forced us to create [this code](https://github.com/netdata/netdata/blob/0586829ee645a672a032b2346d7ea9718e4142af/collectors/ebpf.plugin/ebpf_dcstat.c#L46-L50).

**Review by vlvkobal — APPROVED** [review]

**Pull request merged**
