### PR TITLE
Fix load on kernel 4.14 and older

### PR DESCRIPTION
**Pull request by thiagoftsm**
This PR fixes the ebpf program load on kernel 4.14 and it also brings code optimization

### CODE REVIEW

**Comment by prologic** [comment]
> This pull request is still a work in progress
> Draft pull requests cannot be merged.

**Comment by thiagoftsm** [comment]
I observed that the solution is not covering all problems, there are kernels with problems yet, so I will continue working on this during week.

**Comment by vlvkobal** [comment]
Why did you delete `kprobe/do_exit`? We are using it for [removing elements from a table](https://github.com/netdata/netdata/blob/master/collectors/ebpf.plugin/ebpf_socket.c#L1470-L1471).

**Comment by thiagoftsm** [comment]
> Why did you delete `kprobe/do_exit`? We are using it for [removing elements from a table](https://github.com/netdata/netdata/blob/master/collectors/ebpf.plugin/ebpf_socket.c#L1470-L1471).

When I made the [PR](https://github.com/netdata/netdata/pull/10096) to fix the memory management on ebpf collector, I centralized the cleanup on process side, so this `kprobe` became unnecessary.

**Comment by vlvkobal** [comment]
After the ["ebpf memory cleanup"](https://github.com/netdata/netdata/pull/10096) PR `ebpf_socket_update_apps_data()` is still there and `eb[0].removed` is still in use.

**Comment by thiagoftsm** [comment]
> After the ["ebpf memory cleanup"](https://github.com/netdata/netdata/pull/10096) PR `ebpf_socket_update_apps_data()` is still there and `eb[0].removed` is still in use.

Yes, you are right. The variable is present, because it has relationship with the current version of `ebpf` codes that are running, I will restore now the kprobe and I will remove it with another PR.

On `netdata/netdata` I am centralizing all the process information with `ebpf_process.c` and `ebpf_apps.c`, as you can see on the PR, the `ebpf_socket.c` is only manipulating and storing data, but it does not clean more the unused variables.

**Review by vlvkobal — APPROVED** [review]

**Pull request merged**
