### PR TITLE
Collector improvements and fix 82

### LINKED ISSUE #82: Hash map size
Our collectors were working with hash maps with static size, but when we are monitoring PIDs the hashes can be adjusted. Should we also have a flexible size?

### PR DESCRIPTION
**Pull request by thiagoftsm**
Fixes #82 

This PR brings the possibility to specify hash map size from the collectors. 
It also brings the reset for missing variables.

### CODE REVIEW

**Comment by thiagoftsm** [comment]
> LGTM I _think_; at least it builds. I understand _some_ of the code changes.

Of course you understood, you are becoming a C expert! :D
I also hope in the next years to move from a SRE trainee for your level!

> What I'm not particularly happy about though is our CI only ensures "build success" right now; we have no "unit or integration" testing at all at the moment :/ -- I'm working on e2e/integration testing though so that will help :)

Nice!
I will not merge it yet, because I will wait some reviews from @netdata/core !

**Comment by prologic** [comment]
@amoss Is there someone that has bw to review this too? Otherwise I'll merge it :)

**Comment by thiagoftsm** [comment]
@prologic we need a review on `netdata/netdata` for we merge this, else the collector won't run properly.

**Comment by prologic** [comment]
> @prologic we need a review on `netdata/netdata` for we merge this, else the collector won't run properly.

I'm just getting a bit "itchy" with PR(s) sitting around for more than a week :)

**Comment by thiagoftsm** [comment]
The improvements here were brought with another PR.

**Pull request closed without merging**
