### PR TITLE
Fix chart output independent of the kernel version

### LINKED ISSUE #28: Different charts depending of the kernel version
eBPF is showing different charts depending of the kernel version, this cannot happen.

### PR DESCRIPTION
**Pull request by thiagoftsm**
Fixes #28 

Depending of the kernel version, we had a different charts for process and thread creation. This PR fixes this error.

### CODE REVIEW

**Comment by thiagoftsm** [comment]
Hey @mfundul ,

The eBPF code is running stable and we are almost there to give conditions for everyone to test, but considering your background I already decided to bring you as a reviewer of the eBPF program code.
@Ferroin and @prologic there is already other PR that will take care of the Makefiles here, when we merge it, I will rebase this PR.

Have a nice weekend guys!

**Comment by thiagoftsm** [comment]
I did ran a rebase to remove the Makefile.

**Comment by prologic** [comment]
Also we should fix all teh CI builds :)

**Comment by thiagoftsm** [comment]
@mfundul I merged it for @prologic go in front without the bugs that this PR fixes,  case you find problems with C code, please, let me know that I will create another PR

**Pull request merged**
